# Generated by Django 4.2.4 on 2023-08-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_add_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_country', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_zip', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
    ]
