# Generated by Django 4.2.3 on 2023-07-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_category',
            new_name='category',
        ),
    ]
