# Generated by Django 4.2.3 on 2023-07-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_rename_add_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=20)),
                ('product_quantity', models.CharField(max_length=20)),
                ('product_tag', models.CharField(max_length=50)),
                ('product_image', models.CharField(max_length=20)),
                ('product_short_description', models.TextField()),
                ('product_information', models.TextField()),
                ('product_description', models.TextField()),
            ],
        ),
    ]
