# Generated by Django 4.2.3 on 2023-07-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='admin_product',
        ),
    ]
