# Generated by Django 4.2.3 on 2023-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_rename_product_admin_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=50)),
                ('package_duration', models.CharField(max_length=20)),
                ('package_price', models.CharField(max_length=20)),
                ('package_image', models.CharField(max_length=20)),
                ('package_specification', models.TextField()),
                ('package_description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='category',
            new_name='admin_category',
        ),
    ]
