# Generated by Django 4.2.3 on 2023-07-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_admin_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('class_title', models.CharField(max_length=50)),
                ('class_description', models.CharField(max_length=50)),
                ('class_benefits', models.CharField(max_length=20)),
                ('class_trainer', models.TextField()),
            ],
        ),
    ]
