# Generated by Django 4.2.3 on 2023-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_admin_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('timetable_class', models.CharField(max_length=50)),
                ('timetable_day', models.CharField(max_length=20)),
                ('timetable_starttime', models.CharField(max_length=20)),
                ('timetable_endtime', models.CharField(max_length=20)),
            ],
        ),
    ]
