# Generated by Django 4.2.3 on 2023-07-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_alter_admin_category_cat_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_class',
            name='class_trainer',
        ),
        migrations.AddField(
            model_name='admin_class',
            name='class_image',
            field=models.FileField(default=None, max_length=50, null=True, upload_to='class/'),
        ),
    ]
