# Generated by Django 4.2.3 on 2023-08-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_remove_admin_class_class_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_timetable',
            name='timetable_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.admin_class'),
        ),
    ]
