# Generated by Django 4.2.3 on 2023-08-02 10:23

import customadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_alter_admin_timetable_timetable_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_timetable',
            name='timetable_class',
            field=models.CharField(max_length=20, verbose_name=customadmin.models.admin_class),
        ),
    ]
