# Generated by Django 4.2.3 on 2023-08-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_alter_admin_class_class_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_timetable',
            name='timetable_endtime',
            field=models.TimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admin_timetable',
            name='timetable_starttime',
            field=models.TimeField(max_length=20),
        ),
    ]
