# Generated by Django 4.2.4 on 2023-08-03 19:24

import customadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0014_alter_admin_timetable_timetable_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_product',
            name='product_category',
            field=models.CharField(choices=[(customadmin.models.admin_category, customadmin.models.admin_category)], default='green', max_length=6),
        ),
        migrations.AlterField(
            model_name='admin_product',
            name='product_price',
            field=models.FloatField(max_length=20),
        ),
    ]
