# Generated by Django 4.2.4 on 2023-08-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0015_alter_admin_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_product',
            name='product_category',
            field=models.CharField(max_length=50),
        ),
    ]
