# Generated by Django 4.2.3 on 2023-07-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='u_contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.CharField(max_length=50)),
                ('c_subject', models.CharField(max_length=100)),
                ('c_message', models.CharField(max_length=100)),
            ],
        ),
    ]
