# Generated by Django 4.2.3 on 2023-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_desc', models.CharField(max_length=250)),
                ('book_image', models.FileField(upload_to='book/')),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
            ],
        ),
    ]
