# Generated by Django 3.2.8 on 2021-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('Empid', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=50)),
                ('EmpEmail', models.CharField(max_length=50)),
                ('EmpMobile', models.CharField(max_length=50)),
                ('EmpCity', models.CharField(max_length=50)),
            ],
        ),
    ]
