# Generated by Django 3.2.8 on 2021-10-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpTbl',
            fields=[
                ('Empid', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=50)),
                ('EmpEmail', models.CharField(max_length=50)),
                ('EmpMobile', models.CharField(max_length=50)),
                ('EmpCity', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
